# Generated by Django 6.1.1 on 2026-09-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField()),
                ('result', models.JSONField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=7)),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'tool_name', 'created_at'], name='aal_user_tool_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('SUCCESS', 'FAILURE'))), name='aal_status_ck'), models.CheckConstraint(condition=models.Q(('duration_ms__gte', 0)), name='aal_duration_ck')],
            },
        ),
    ]
