# Generated by Django 6.1.1 on 2026-09-25 14:11

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('model_year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=32)),
                ('current_mileage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('license_plate'), name='vehicles_plate_ci_uniq'), models.CheckConstraint(condition=models.Q(('current_mileage__gte', 0)), name='vehicles_mileage_gte_0')],
            },
        ),
    ]
