# Generated by Django 6.1.1 on 2026-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('part_number',), name='inventory_part_number_uniq'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_part_quantity_gte_0'), models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='inventory_min_stock_gte_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='inventory_unit_price_gte_0')],
            },
        ),
    ]
