# Generated by Django 6.1.1 on 2026-09-25 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('inventory', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('interval_km', models.PositiveIntegerField()),
                ('interval_months', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='maintenance_service_name_uniq'), models.CheckConstraint(condition=models.Q(('interval_km__gt', 0)), name='maintenance_interval_km_gt_0'), models.CheckConstraint(condition=models.Q(('interval_months__gt', 0)), name='maintenance_interval_months_gt_0'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='maintenance_duration_gt_0'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='maintenance_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='appointments.appointment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='maintenance.servicetype')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='maintenance.technicianprofile')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_parts', to='inventory.sparepart')),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_parts', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('maintenance_record', 'spare_part'), name='maintenance_record_part_uniq'), models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='maintenance_part_quantity_gt_0')],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'service_date'], name='maintenance_vehicle_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('mileage_at_service__gte', 0)), name='maintenance_record_mileage_gte_0'),
        ),
    ]
