# Generated by Django 6.1.1 on 2026-09-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='maintenance.servicetype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='maintenance.technicianprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='serviceslot',
            index=models.Index(fields=['start_time'], name='appointments_slot_start_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceslot',
            index=models.Index(fields=['is_active', 'start_time'], name='appointments_active_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointments_slot_end_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='serviceslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='appointments_slot_capacity_gt_0'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.serviceslot'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['slot', 'status'], name='appointments_slot_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'])), name='appointments_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'CONFIRMED', 'IN_PROGRESS'))), fields=('slot', 'vehicle'), name='appointments_active_slot_vehicle_uniq'),
        ),
    ]
